### Validate user and password and get token
POST https://dummyjson.com/auth/login?delay=1000
content-type: application/json

{
    "username": "emilys",
    "password": "emilyspass"
}

### Get all categories with token
GET https://dummyjson.com/auth/products/categories?delay=1000
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJlbWlseXMiLCJlbWFpbCI6ImVtaWx5LmpvaG5zb25AeC5kdW1teWpzb24uY29tIiwiZmlyc3ROYW1lIjoiRW1pbHkiLCJsYXN0TmFtZSI6IkpvaG5zb24iLCJnZW5kZXIiOiJmZW1hbGUiLCJpbWFnZSI6Imh0dHBzOi8vZHVtbXlqc29uLmNvbS9pY29uL2VtaWx5cy8xMjgiLCJpYXQiOjE3NjM1MzcwNjcsImV4cCI6MTc2MzU0MDY2N30.dwECqJUdtnGuCEApsZHmWVN1e02QbnmePaLQywI_4vo

### Get all products of a category with token
GET https://dummyjson.com/auth/products/category/beauty
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJlbWlseXMiLCJlbWFpbCI6ImVtaWx5LmpvaG5zb25AeC5kdW1teWpzb24uY29tIiwiZmlyc3ROYW1lIjoiRW1pbHkiLCJsYXN0TmFtZSI6IkpvaG5zb24iLCJnZW5kZXIiOiJmZW1hbGUiLCJpbWFnZSI6Imh0dHBzOi8vZHVtbXlqc29uLmNvbS9pY29uL2VtaWx5cy8xMjgiLCJpYXQiOjE3NjM1MzcwNjcsImV4cCI6MTc2MzU0MDY2N30.dwECqJUdtnGuCEApsZHmWVN1e02QbnmePaLQywI_4vo
