### Validate user and password and get token
POST https://dummyjson.com/auth/login?delay=1000
content-type: application/json

{
    "username": "emilys",
    "password": "emilyspass"
}

### Get all categories with token
GET https://dummyjson.com/auth/products/categories?delay=1000
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJlbWlseXMiLCJlbWFpbCI6ImVtaWx5LmpvaG5zb25AeC5kdW1teWpzb24uY29tIiwiZmlyc3ROYW1lIjoiRW1pbHkiLCJsYXN0TmFtZSI6IkpvaG5zb24iLCJnZW5kZXIiOiJmZW1hbGUiLCJpbWFnZSI6Imh0dHBzOi8vZHVtbXlqc29uLmNvbS9pY29uL2VtaWx5cy8xMjgiLCJpYXQiOjE3NjM2Mzk4MzUsImV4cCI6MTc2MzY0MzQzNX0.C92W641VYxZX1Spfz0ovd13OfZnetXVYVvrao4PdMCQ

### Get all products of a category with token
GET https://dummyjson.com/auth/products/category/beauty?delay=1000&select=id,title,thumbnail
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJlbWlseXMiLCJlbWFpbCI6ImVtaWx5LmpvaG5zb25AeC5kdW1teWpzb24uY29tIiwiZmlyc3ROYW1lIjoiRW1pbHkiLCJsYXN0TmFtZSI6IkpvaG5zb24iLCJnZW5kZXIiOiJmZW1hbGUiLCJpbWFnZSI6Imh0dHBzOi8vZHVtbXlqc29uLmNvbS9pY29uL2VtaWx5cy8xMjgiLCJpYXQiOjE3NjM2Mzk4MzUsImV4cCI6MTc2MzY0MzQzNX0.C92W641VYxZX1Spfz0ovd13OfZnetXVYVvrao4PdMCQ

### Get a product with token
GET https://dummyjson.com/auth/products/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJlbWlseXMiLCJlbWFpbCI6ImVtaWx5LmpvaG5zb25AeC5kdW1teWpzb24uY29tIiwiZmlyc3ROYW1lIjoiRW1pbHkiLCJsYXN0TmFtZSI6IkpvaG5zb24iLCJnZW5kZXIiOiJmZW1hbGUiLCJpbWFnZSI6Imh0dHBzOi8vZHVtbXlqc29uLmNvbS9pY29uL2VtaWx5cy8xMjgiLCJpYXQiOjE3NjM2Mzk4MzUsImV4cCI6MTc2MzY0MzQzNX0.C92W641VYxZX1Spfz0ovd13OfZnetXVYVvrao4PdMCQ
